### ISSUE TITLE
Using a shield belt while holding a ranged weapon causes errors when trying to train

### ISSUE THREAD

**Issue by krypto5863** [emipa606/CombatTraining#1]
I know it's a little counter-intuitive but I noticed one of my settlers was freezing in place and not doing much and my FPS was a little dicey, looked in the log and noticed she was trying to train but failing to even start the task.

Turns out she had a shield belt with a BB gun and that was causing an error. Removing the belt fixed the issue.

**Comment by emipa606** [comment]
Fixed in 4d3c500
Thanks for the report!
